added studentExercises.json

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -50,38 +50,25 @@ fi
 # Build the React project
 npm run build
 
-# Check if the bucket exists
-USER_BUCKET_NAME="user-$(git config user.name | tr '[:upper:]' '[:lower:]')-$(git symbolic-ref --short HEAD | tr '/' '-')"
-if aws s3api head-bucket --bucket $USER_BUCKET_NAME --profile AccountLevelFullAccess-503226040441 2>/dev/null; then
-  echo "Bucket already exists: $USER_BUCKET_NAME"
-else
-  echo "Creating bucket: $USER_BUCKET_NAME"
-  aws s3api create-bucket --bucket $USER_BUCKET_NAME --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1 --profile AccountLevelFullAccess-503226040441
-  aws s3api put-public-access-block --bucket $USER_BUCKET_NAME --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false" --profile AccountLevelFullAccess-503226040441
-  aws s3api put-bucket-policy --bucket $USER_BUCKET_NAME --policy '{
-    "Version": "2012-10-17",
-    "Statement": [
-      {
-        "Effect": "Allow",
-        "Principal": "*",
-        "Action": "s3:GetObject",
-        "Resource": "arn:aws:s3:::'"$USER_BUCKET_NAME"'/*"
-      }
-    ]
-  }' --profile AccountLevelFullAccess-503226040441
-  aws s3api put-bucket-website --bucket $USER_BUCKET_NAME --website-configuration '{
-    "ErrorDocument": {"Key": "index.html"},
-    "IndexDocument": {"Suffix": "index.html"}
-  }' --profile AccountLevelFullAccess-503226040441
+# Check if the build was successful
+if [ $? -ne 0 ]; then
+  echo "Build failed. Cannot upload to S3 bucket."
+  exit 1
 fi
 
-# Deploy the build to the user's branch-specific bucket
-aws s3 sync build/ s3://$USER_BUCKET_NAME --profile AccountLevelFullAccess-503226040441
+# Set S3 bucket and folder variables
+S3_BUCKET="kdu-automation"
+FOLDER_NAME="builds"
+S3_FOLDER="$USERNAME-$BRANCH_NAME"
+
+# Upload build contents to S3 bucket
+aws s3 sync ./build "s3://$S3_BUCKET/$FOLDER_NAME/$S3_FOLDER" --delete --profile AccountLevelFullAccess-503226040441
+
+USER_BUCKET_NAME="user-$(git config user.name | tr '[:upper:]' '[:lower:]')-$(git symbolic-ref --short HEAD | tr '/' '-')"
 
 # Generate the deployment URL
 DEPLOYMENT_URL="http://$USER_BUCKET_NAME.s3-website.ap-south-1.amazonaws.com"
 echo "Deployment URL: $DEPLOYMENT_URL"
-
 
 
 # Function to check if the JSON file exists in the bucket
@@ -114,8 +101,10 @@ add_key_value_to_json() {
 
 
 # Update JSON file with the deployment URL
-
-FILENAME="submissions.json"
+USERNAME=$(git config user.name)
+#BRANCH_NAME=$(git symbolic-ref --short HEAD)
+BRANCH_NAME=$(git symbolic-ref --short HEAD)
+FILENAME="studentExercises.json"
 
 # Check if the JSON file exists in the bucket
 if check_json_file_exists "$FILENAME"; then
@@ -137,5 +126,13 @@ aws s3 cp ./temp.json "s3://kdu-automation/frontend/$FILENAME" --profile Account
 
 echo "JSON file uploaded successfully."
 
-#remove the temporary file
-rm ./temp.json
+# Check if the upload was successful
+if [ $? -eq 0 ]; then
+  echo "Build uploaded to S3 bucket successfully."
+else
+  echo "Failed to upload the build to S3 bucket. Please check the logs for more details."
+fi
+
+
+
+
